import { cn } from "@/lib/utils"
import "./globals.css"
import type { Metadata } from "next"
import { Inter, Poppins } from "next/font/google"
import Navbar from "@/components/Navbar"
import Providers from "@/components/Providers"
import ConditionalNavbar from "@/components/ConditionalNavbar"

const inter = Inter({ subsets: ["latin"] })
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang='en'
      className={`light ${poppins.variable}`}
    >
      <Providers>
        <body
          className={cn(
            "min-h-screen font-sans antialiased",
            poppins.className
          )}
        >
          <ConditionalNavbar />
          {children}
        </body>
      </Providers>
    </html>
  )
}
